#
# Copyright (C) 2014  Rudolf Tammekivi <rtammekivi@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# This file is generated by device/huawei/u8860/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
	vendor/huawei/u8860/proprietary/system/lib/libaudcal.so:obj/lib/libaudcal.so \
	vendor/huawei/u8860/proprietary/system/lib/libaudioalsa.so:obj/lib/libaudioalsa.so

PRODUCT_COPY_FILES += \
	vendor/huawei/u8860/proprietary/system/lib/libaudcal.so:system/lib/libaudcal.so \
	vendor/huawei/u8860/proprietary/system/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
	vendor/huawei/u8860/proprietary/system/bin/cnd:system/bin/cnd \
	vendor/huawei/u8860/proprietary/system/bin/netmgrd:system/bin/netmgrd \
	vendor/huawei/u8860/proprietary/system/bin/qmuxd:system/bin/qmuxd \
	vendor/huawei/u8860/proprietary/system/lib/libril-qc-1.so:system/lib/libril-qc-1.so \
	vendor/huawei/u8860/proprietary/system/lib/libauth.so:system/lib/libauth.so \
	vendor/huawei/u8860/proprietary/system/lib/libcm.so:system/lib/libcm.so \
	vendor/huawei/u8860/proprietary/system/lib/libcneqmiutils.so:system/lib/libcneqmiutils.so \
	vendor/huawei/u8860/proprietary/system/lib/libcneutils.so:system/lib/libcneutils.so \
	vendor/huawei/u8860/proprietary/system/lib/libdiag.so:system/lib/libdiag.so \
	vendor/huawei/u8860/proprietary/system/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
	vendor/huawei/u8860/proprietary/system/lib/libdsm.so:system/lib/libdsm.so \
	vendor/huawei/u8860/proprietary/system/lib/libdsutils.so:system/lib/libdsutils.so \
	vendor/huawei/u8860/proprietary/system/lib/libhwrpc.so:system/lib/libhwrpc.so \
	vendor/huawei/u8860/proprietary/system/lib/libidl.so:system/lib/libidl.so \
	vendor/huawei/u8860/proprietary/system/lib/libnetmgr.so:system/lib/libnetmgr.so \
	vendor/huawei/u8860/proprietary/system/lib/libnv.so:system/lib/libnv.so \
	vendor/huawei/u8860/proprietary/system/lib/liboncrpc.so:system/lib/liboncrpc.so \
	vendor/huawei/u8860/proprietary/system/lib/libpbmlib.so:system/lib/libpbmlib.so \
	vendor/huawei/u8860/proprietary/system/lib/libqdi.so:system/lib/libqdi.so \
	vendor/huawei/u8860/proprietary/system/lib/libqdp.so:system/lib/libqdp.so \
	vendor/huawei/u8860/proprietary/system/lib/libqmiservices.so:system/lib/libqmiservices.so \
	vendor/huawei/u8860/proprietary/system/lib/libqmi.so:system/lib/libqmi.so \
	vendor/huawei/u8860/proprietary/system/lib/libqueue.so:system/lib/libqueue.so \
	vendor/huawei/u8860/proprietary/system/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
	vendor/huawei/u8860/proprietary/system/lib/libwms.so:system/lib/libwms.so \
	vendor/huawei/u8860/proprietary/system/lib/libwmsts.so:system/lib/libwmsts.so \
	vendor/huawei/u8860/proprietary/system/lib/libxml.so:system/lib/libxml.so \
	vendor/huawei/u8860/proprietary/system/bin/modempre:system/bin/modempre \
	vendor/huawei/u8860/proprietary/system/bin/oem_rpc_svc:system/bin/oem_rpc_svc \
	vendor/huawei/u8860/proprietary/system/lib/liboem_rapi.so:system/lib/liboem_rapi.so \
	vendor/huawei/u8860/proprietary/system/etc/wifi/bcmdhd.cal:system/etc/wifi/bcmdhd.cal \
	vendor/huawei/u8860/proprietary/system/vendor/firmware/bcm4329.hcd:system/vendor/firmware/bcm4329.hcd
