#
# Copyright (C) 2014  Rudolf Tammekivi <rtammekivi@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# This file is generated by device/huawei/u8800/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
	vendor/huawei/u8800/proprietary/system/lib/libaudcal.so:obj/lib/libaudcal.so \
	vendor/huawei/u8800/proprietary/system/lib/libaudioalsa.so:obj/lib/libaudioalsa.so \
	vendor/huawei/u8800/proprietary/system/lib/libnv.so:obj/lib/libnv.so \
	vendor/huawei/u8800/proprietary/system/lib/liboncrpc.so:obj/lib/liboncrpc.so

PRODUCT_COPY_FILES += \
	vendor/huawei/u8800/proprietary/system/lib/libaudcal.so:system/lib/libaudcal.so \
	vendor/huawei/u8800/proprietary/system/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
	vendor/huawei/u8800/proprietary/system/bin/cnd:system/bin/cnd \
	vendor/huawei/u8800/proprietary/system/bin/netmgrd:system/bin/netmgrd \
	vendor/huawei/u8800/proprietary/system/bin/qmuxd:system/bin/qmuxd \
	vendor/huawei/u8800/proprietary/system/lib/libril-qc-1.so:system/lib/libril-qc-1.so \
	vendor/huawei/u8800/proprietary/system/lib/libauth.so:system/lib/libauth.so \
	vendor/huawei/u8800/proprietary/system/lib/libcm.so:system/lib/libcm.so \
	vendor/huawei/u8800/proprietary/system/lib/libdiag.so:system/lib/libdiag.so \
	vendor/huawei/u8800/proprietary/system/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
	vendor/huawei/u8800/proprietary/system/lib/libdsm.so:system/lib/libdsm.so \
	vendor/huawei/u8800/proprietary/system/lib/libdsutils.so:system/lib/libdsutils.so \
	vendor/huawei/u8800/proprietary/system/lib/libgsdi_exp.so:system/lib/libgsdi_exp.so \
	vendor/huawei/u8800/proprietary/system/lib/libgstk_exp.so:system/lib/libgstk_exp.so \
	vendor/huawei/u8800/proprietary/system/lib/libhwrpc.so:system/lib/libhwrpc.so \
	vendor/huawei/u8800/proprietary/system/lib/libidl.so:system/lib/libidl.so \
	vendor/huawei/u8800/proprietary/system/lib/libmmgsdilib.so:system/lib/libmmgsdilib.so \
	vendor/huawei/u8800/proprietary/system/lib/libnetmgr.so:system/lib/libnetmgr.so \
	vendor/huawei/u8800/proprietary/system/lib/libnv.so:system/lib/libnv.so \
	vendor/huawei/u8800/proprietary/system/lib/liboncrpc.so:system/lib/liboncrpc.so \
	vendor/huawei/u8800/proprietary/system/lib/libpbmlib.so:system/lib/libpbmlib.so \
	vendor/huawei/u8800/proprietary/system/lib/libqdp.so:system/lib/libqdp.so \
	vendor/huawei/u8800/proprietary/system/lib/libqmi.so:system/lib/libqmi.so \
	vendor/huawei/u8800/proprietary/system/lib/libqueue.so:system/lib/libqueue.so \
	vendor/huawei/u8800/proprietary/system/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
	vendor/huawei/u8800/proprietary/system/lib/libwms.so:system/lib/libwms.so \
	vendor/huawei/u8800/proprietary/system/lib/libwmsts.so:system/lib/libwmsts.so \
	vendor/huawei/u8800/proprietary/system/etc/firmware/wlan/cfg.dat:system/etc/firmware/wlan/cfg.dat \
	vendor/huawei/u8800/proprietary/system/etc/firmware/wlan/qcom_cfg.ini:system/etc/firmware/wlan/qcom_cfg.ini \
	vendor/huawei/u8800/proprietary/system/etc/firmware/wlan/qcom_fw.bin:system/etc/firmware/wlan/qcom_fw.bin \
	vendor/huawei/u8800/proprietary/system/etc/firmware/wlan/qcom_wapi_fw.bin:system/etc/firmware/wlan/qcom_wapi_fw.bin \
	vendor/huawei/u8800/proprietary/system/etc/firmware/wlan/qcom_wlan_nv.bin:system/etc/firmware/wlan/qcom_wlan_nv.bin \
	vendor/huawei/u8800/proprietary/system/lib/modules/wlan.ko:system/lib/modules/wlan.ko \
	vendor/huawei/u8800/proprietary/system/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
	vendor/huawei/u8800/proprietary/system/lib/libchromatix_s5k4e1gx_p_default_video.so:system/lib/libchromatix_s5k4e1gx_p_default_video.so \
	vendor/huawei/u8800/proprietary/system/lib/libchromatix_s5k4e1gx_p_preview.so:system/lib/libchromatix_s5k4e1gx_p_preview.so \
	vendor/huawei/u8800/proprietary/system/lib/libchromatix_ov5647_sunny_preview.so:system/lib/libchromatix_ov5647_sunny_preview.so \
	vendor/huawei/u8800/proprietary/system/lib/libchromatix_ov5647_sunny_default_video.so:system/lib/libchromatix_ov5647_sunny_default_video.so \
	vendor/huawei/u8800/proprietary/system/lib/libgemini.so:system/lib/libgemini.so \
	vendor/huawei/u8800/proprietary/system/lib/libmmipl.so:system/lib/libmmipl.so \
	vendor/huawei/u8800/proprietary/system/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
	vendor/huawei/u8800/proprietary/system/lib/liboemcamera.so:system/lib/liboemcamera.so \
	vendor/huawei/u8800/proprietary/system/bin/fm_qsoc_patches:system/bin/fm_qsoc_patches \
	vendor/huawei/u8800/proprietary/system/lib/libqmiservices.so:system/lib/libqmiservices.so
